workspace:
  base: /go
  path: src/github.com/journeymidnight/kdt

pipeline:
  build:
    image: thesues/kdt
    commands:
      - "go get ./..."
      - "bash build.sh"

  pushbear:
    image: thesues/drone-pushbear
    secrets: [sendkey]
    when:
      status: [success, failure]

  github_release:
    image: plugins/github-release
    files:
      - "gui/out/*.tar.gz"
      - "*.tar.gz"
    secrets: [github_token]
    when:
      event: [tag]
