sudo: required 
dist: trusty    
language: go
go:
  - 1.8
before_install:
  - "curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -"
  - "sudo apt-get update && sudo apt-get install -y --no-install-recommends nodejs"
  - "sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y --no-install-recommends wine wine1.6-i386"
  - "sudo npm install electron-packager -g"
script:
  - "go get ./..." 
  - "bash build.sh"
deploy:
  provider: releases
  api_key:
    secure: "ieIgKufZZEHlKESSHLPjsHFVvIpM8lwTzW8dr39VkkhJ2N1OCPE0IC0Ijv8EhHZqAB2XwzxZZ0KTXYI8G6H28x4HQAjonMNc6wzcgjm0lh66IiyZ/372bkyJRwpWu0zw2XmWqvoWrsG+O0X1E6b9WaAJYlsaIHY8X7B8sOKpHPG9kMH+ELyBStx91z/54TOydC85bXuqBNcGns+3lcA7IBrOUdwKNiG8P6oRpKHlrGK0S8rTUod3KNd5HgFZPQ6lffaMc1zAJUEP3EPHhVa0deL9EzIfW+YVI1ZqkKpCRMnoDc9JV601EK+DnlptbplzQ6TTU+1n4BMCNNjaAzUAPDLYBoZvHMkzE4TLBzlyhIK5DJgpnFhCf46R9U3z+5W9kDe+HIZNuiKSTE5bIucH05Y+834z8B/vAWMTtk2B+G7AvEUWnEqznRSNz2stK0Ttve0HR3HlY5aecP91+zX1UO72Lq/NszHY/4r2HFCm/D1VSXCIcncwlkBCCIKo9BFndeNpObDABZx+80faRaP+lAZWpTMXWS0HoSpmljRnTW+UqAahhzuPr/ajTgE821y2874Fwfr2GUTmcfg39QYEgYW1/IipbhEYXstd58dPc1NHMvuddCMThPvmLMdYhXfz1Dr6+mqZ///B8DYi4FbAS9F+K00e52cEWlYQk96AsYg="
  file_glob: true
  file:
    - "gui/out/*.tar.gz"
    - "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
